import numpy as np
import matplotlib.pyplot as plt
from scipy import signal
fs=500
t=np.linspace(-1, 1, fs, endpoint=False)
unit_step=np.heaviside(t, 1)
unit_impulse=np.zeros_like(t)
unit_impulse[fs//2]=1
ramp_signal=signal.sawtooth(2*np.pi*t,1)
f_sine=5
sine_wave=np.sin(2*np.pi*f_sine*t)
f_cosine=5
cosine_wave=np.cos(2*np.pi*f_cosine*t)
exponential_signal=np.exp(t)
triangular_wave=signal.sawtooth(2*np.pi*5*t,0.5)
square_wave = signal.square(2 * np.pi * 5 * t)
# Plot the signals
plt.figure()
plt.subplot(4, 2, 1)
plt.plot(t, unit_step)
plt.title('Unit Step Signal')
plt.xlabel('Time [s]')
plt.ylabel('Amplitude')
plt.subplot(4, 2, 2)
plt.plot(t, unit_impulse)
plt.title('Unit Impulse Signal')
plt.xlabel('Time [s]')
plt.ylabel('Amplitude')
plt.subplot(4, 2, 3)
plt.plot(t, ramp_signal)
plt.title('Ramp Signal')
plt.xlabel('Time [s]')
plt.ylabel('Amplitude')
plt.subplot(4, 2, 4)
plt.plot(t, sine_wave)
plt.title('Sine Wave')
plt.xlabel('Time [s]')
plt.ylabel('Amplitude')
plt.subplot(4, 2, 5)
plt.plot(t, cosine_wave)
plt.title('Cosine Wave')
plt.xlabel('Time [s]')
plt.ylabel('Amplitude')
plt.subplot(4, 2, 6)
plt.plot(t, exponential_signal)
plt.title('Exponential Signal')
plt.xlabel('Time [s]')
plt.ylabel('Amplitude')
plt.subplot(4, 2, 7)
plt.plot(t, triangular_wave)
plt.title('Triangular Wave')
plt.xlabel('Time [s]')
plt.ylabel('Amplitude')
plt.subplot(4, 2, 8)
plt.plot(t, square_wave)
plt.title('Square Wave')
plt.xlabel('Time [s]')
plt.ylabel('Amplitude')
plt.tight_layout()
plt.show()